server:
  port: 0

spring:
  application:
    name: NOTIFICATION-SERVICE

  sleuth:
    integration:
      enabled: true
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/

  kafka :
    bootstrap-servers : localhost:9092
    template :
      default-topic : notificationTopic
    consumer :
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties :
        "[spring.json.type.mapping]" : event:com.notificationservice.event.OrderPlacedEvent
      value-deserializer : org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka

#actuator prometheus endpoint

management:
  endpoints:
    web:
      exposure:
        include: prometheus

