eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761

spring:
  zipkin :
    base-url : http://localhost:9411
  sleuth :
    sampler :
      probability : 1.0

#actuator prometheus endpoint

management:
  endpoints:
    web:
      exposure:
        include: prometheus

