spring:
  data:
    mongodb:
      database: ProductService
      host: localhost
      port: 27017
  application:
    name: PRODUCT-SERVICE

  zipkin :
    base-url : http://localhost:9411
  sleuth :
    sampler :
      probability : 1.0

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka

server:
  port: 0

#actuator prometheus endpoint

management:
  endpoints:
    web:
      exposure:
        include: prometheus