spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventoryservice
    username: root
    password: Omkar66527
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: INVENTORY-SERVICE

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  zipkin :
    base-url : http://localhost:9411
  sleuth :
    sampler :
      probability : 1.0

server:
  port: 0

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka

#actuator prometheus endpoint

management:
  endpoints:
    web:
      exposure:
        include: prometheus
